[package]
name = "sara_ecs"
description = "A simple ecs library made for study purposes."
authors = ["Sara01"]
license = "Apache-2.0"
version = "0.2.1"
edition = "2021"

[dependencies]
thiserror = "2.0.7"
